site:
  title: Integreatly Docs
  start_page: docs::getting-started.adoc

content:
  sources:
    - url: ../i8y-antora
      branches: HEAD

ui:
  bundle:
    url: ./i8y-ui-bundle/build/ui-bundle.zip

urls:
  redirect_facility: disabled

output:
  dir: ./static
